// Copyright 2023 Mykhailo Mushynskyi. All rights reserved.

namespace KrakenUI
{
    [default_interface]
    runtimeclass MainWindow : Microsoft.UI.Xaml.Window
    {
        MainWindow();

        Microsoft.UI.Windowing.AppWindow GetNativeWindow();
    }
}
