// Copyright 2023 Mykhailo Mushynskyi. All rights reserved.
namespace KrakenUI
{
    [default_interface]
    runtimeclass EditorPage : Microsoft.UI.Xaml.Controls.Page
    {
        EditorPage();
    }
}
